"""
test.py — Batch evaluation harness for SQL-agent

Runs a fixed set of test questions against the agent, captures the agent's
final answer, and logs everything to a CSV. You then fill in a ✅/❌/⚠️
correctness column by eye (or compare against the "expected_answer" hints
provided below) to compute an accuracy score for your README/LinkedIn post.

Usage:
    python test.py

Place this file in the same folder as agent.py and model.py.
"""

import os
import csv
import time
from dotenv import load_dotenv

load_dotenv()

from langchain_community.utilities import SQLDatabase
from langchain_community.agent_toolkits import create_sql_agent
from model import model

# ---------------------------------------------------------------------------
# 1. Connect to the SQLite Database (same as agent.py)
# ---------------------------------------------------------------------------
db_path = "Chinook.db"
if not os.path.exists(db_path):
    print(f"Error: Database {db_path} not found. Please ensure it exists.")
    exit(1)

db = SQLDatabase.from_uri(f"sqlite:///{db_path}")

print("Initializing SQL Agent...")
agent_executor = create_sql_agent(
    llm=model,
    db=db,
    verbose=False,  # set True if you want to see the full ReAct trace per question
)

# ---------------------------------------------------------------------------
# 2. Test questions
#
# "expected_answer" is a human-readable hint for YOU to judge correctness
# against — it is NOT fed to the agent, and for some Tier 5 questions there
# isn't one fixed right answer (that's the point — see notes).
# ---------------------------------------------------------------------------
test_questions = [
    # Tier 1: Simple lookups
    {"tier": 1, "question": "How many tracks are there in the database?",
     "expected_answer": "3503"},
    {"tier": 1, "question": "List all the genres available.",
     "expected_answer": "25 genres, e.g. Rock, Jazz, Metal, Alternative & Punk, etc."},
    {"tier": 1, "question": "What is the email address of the customer named Helena Holý?",
     "expected_answer": "hholy@gmail.com"},
    {"tier": 1, "question": "How many employees are there?",
     "expected_answer": "8"},
    {"tier": 1, "question": "What is the most expensive track in the database?",
     "expected_answer": "Check UnitPrice column — most tracks are 0.99, some are 1.99 (TV/video tracks)"},

    # Tier 2: Single join
    {"tier": 2, "question": "List all albums by the artist AC/DC.",
     "expected_answer": "For Those About To Rock We Salute You, Let There Be Rock"},
    {"tier": 2, "question": "Which customers are from Brazil?",
     "expected_answer": "5 customers from Brazil"},
    {"tier": 2, "question": 'What tracks belong to the album "Let There Be Rock"?',
     "expected_answer": "9 tracks"},
    {"tier": 2, "question": "Show the total number of tracks in each genre.",
     "expected_answer": "Rock has the most (~1297), then Latin, Metal, etc."},
    {"tier": 2, "question": "Which employee reports to which manager?",
     "expected_answer": "Check Employee.ReportsTo self-join — Andrew Adams is the top-level manager"},

    # Tier 3: Multi-table joins
    {"tier": 3, "question": "What is the total revenue generated by each country?",
     "expected_answer": "USA highest (~523.06), then Canada, France, Brazil..."},
    {"tier": 3, "question": "List the top 5 customers by total amount spent.",
     "expected_answer": "Top spender is typically Helena Holý or Richard Cunningham (~144-150)"},
    {"tier": 3, "question": "Which artist has the most albums in the database?",
     "expected_answer": "Iron Maiden (21 albums)"},
    {"tier": 3, "question": 'Which customers are who have purchased tracks from the genre "Jazz"?',
     "expected_answer": "Check via Invoice -> InvoiceLine -> Track -> Genre join"},
    {"tier": 3, "question": "Show the total sales per employee, based on the customers they support.",
     "expected_answer": "Jane Peacock, Margaret Park, Steve Johnson are the 3 support reps"},

    # Tier 4: Aggregation + filtering
    {"tier": 4, "question": "What is the average invoice total, grouped by country, for countries with more than 5 invoices?",
     "expected_answer": "USA, Canada, France, Brazil, Germany likely qualify"},
    {"tier": 4, "question": "Which genre has generated the most revenue overall?",
     "expected_answer": "Rock"},
    {"tier": 4, "question": "Find the top 3 best-selling tracks by quantity sold.",
     "expected_answer": "Several tracks tied at quantity=2 — check InvoiceLine grouped by TrackId"},
    {"tier": 4, "question": "List customers who have spent more than $40 in total.",
     "expected_answer": "Small subset of the 59 customers"},
    {"tier": 4, "question": "Which album has the highest number of tracks, and who is the artist?",
     "expected_answer": "Greatest Hits by Lenny Kravitz, or check for highest count explicitly"},

    # Tier 5: Ambiguous / tricky natural language
    {"tier": 5, "question": "Who are my best customers?",
     "expected_answer": "Open-ended — judge whether it reasonably infers 'spending' as the ranking metric"},
    {"tier": 5, "question": "What's popular right now?",
     "expected_answer": "Open-ended / unanswerable as stated — judge whether it asks for clarification vs. hallucinates"},
    {"tier": 5, "question": "Show me something about rock music.",
     "expected_answer": "Open-ended — judge whether it picks a sensible, non-overwhelming response (e.g. top rock tracks/albums)"},
    {"tier": 5, "question": "Compare sales between USA and Canada.",
     "expected_answer": "Should produce two comparable revenue figures"},
    {"tier": 5, "question": "Did sales go up or down over time?",
     "expected_answer": "Requires reasoning over InvoiceDate — judge whether it finds and uses the date column correctly"},
]

# ---------------------------------------------------------------------------
# 3. Run all questions and log results
# ---------------------------------------------------------------------------
results = []

for i, item in enumerate(test_questions, start=1):
    tier = item["tier"]
    question = item["question"]
    expected = item["expected_answer"]

    print(f"\n[{i}/{len(test_questions)}] (Tier {tier}) {question}")

    start_time = time.time()
    try:
        result = agent_executor.invoke({"input": question})
        answer = result.get("output", str(result))
        error = ""
    except Exception as e:
        answer = ""
        error = str(e)
        print(f"  -> ERROR: {error}")

    elapsed = round(time.time() - start_time, 2)

    print(f"  -> Answer: {answer}")
    print(f"  -> Expected (hint): {expected}")
    print(f"  -> Time: {elapsed}s")

    results.append({
        "index": i,
        "tier": tier,
        "question": question,
        "agent_answer": answer,
        "expected_answer_hint": expected,
        "time_seconds": elapsed,
        "error": error,
        "correctness": "",  # fill in manually: correct / wrong / partial
    })

# ---------------------------------------------------------------------------
# 4. Write to CSV
# ---------------------------------------------------------------------------
output_file = "test_results.csv"
fieldnames = [
    "index", "tier", "question", "agent_answer",
    "expected_answer_hint", "time_seconds", "error", "correctness",
]

with open(output_file, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(results)

print(f"\n\nDone. Results written to {output_file}")
print("Open the CSV and fill in the 'correctness' column with: correct / wrong / partial")
print("Then compute accuracy as: correct_count / total_count")

# ---------------------------------------------------------------------------
# 5. Quick summary printout
# ---------------------------------------------------------------------------
print("\n--- Summary ---")
for tier_num in sorted(set(r["tier"] for r in results)):
    tier_results = [r for r in results if r["tier"] == tier_num]
    errors = sum(1 for r in tier_results if r["error"])
    print(f"Tier {tier_num}: {len(tier_results)} questions, {errors} hard errors")